### ISSUE TITLE
About the  DeformingThings4D datasets

### ISSUE THREAD

**Issue by 2019EPWL** [sergeyprokudin/sergeyprokudin.github.io#2]
Hi, thank you for your excellent work, I would like to ask how to deal with the original XXX.anime to generate DeformingThings4D point cloud.

**Comment by sergeyprokudin** [comment]
Hi @2019EPWL, take a look at the [anime_reader](https://github.com/rabbityl/DeformingThings4D/blob/7cb946173968d88419b7432139f4be682cf61622/code/anime_renderer.py#L83) function from the original code. This code will allow you to create a mesh. You can them sample points from it by using e.g. [pytorch3d](https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/ops/sample_points_from_meshes.html) or [trimesh](https://trimsh.org/trimesh.sample.html) sampling functions. 

Hope this helps

~Sergey

**Comment by 2019EPWL** [comment]
Thank you very much！
